### ISSUE TITLE
Errors like "debconf: unable to initialize frontend: Dialog" appear if ENV DEBIAN_FRONTEND noninteractive is not set

### ISSUE THREAD

**Issue by SohamChakraborty** [turnbullpress/dockerbook-code#35]
Hi, 

Without using *ENV DEBIAN_FRONTEND noninteractive* in Dockerfile, the build process spews out messages like: 

`debconf: unable to initialize frontend: Dialog`
`debconf: (TERM is not set, so the dialog frontend is not usable.)`
`debconf: falling back to frontend: Readline`
`debconf: unable to initialize frontend: Readline`
`debconf: (This frontend requires a controlling tty.)`
`debconf: falling back to frontend: Teletype`
`dpkg-preconfigure: unable to re-open stdin: `

I don't see any Dockerfile with the 'ENV DEBIAN_FRONTEND noninteractive' line. Is this something to include in the Dockerfile, James?

**Comment by jamtur01** [comment]
Sure. I don't usually bother as the error is harmless but you can add it if you like.
