### ISSUE TITLE
Error starting redis on Mac

### ISSUE THREAD

**Issue by rpd10** [turnbullpress/dockerbook-code#41]
I'm using version 17.03.0 of the Docker Book, on a Mac.  In Chapter 5, in the section Building a Redis database image, on page 160 I'm getting an error when starting the redis container.

Here is my Dockerfile:
```
FROM ubuntu:16.04
ENV REFRESHED_AT 2017-04-06
RUN apt-get -yqq update; apt-get -yqq install redis-server redis-tools
EXPOSE 6379
ENTRYPOINT ["/usr/bin/redis-server", "--protected-mode no" ] 
CMD []
```

The docker image builds successfully, when I try to run it, the container starts and then exits immediately.  docker logs shows:
```
*** FATAL CONFIG FILE ERROR ***
Reading the configuration file, at line 2
>>> 'protected-mode no'
Bad directive or wrong number of arguments
```

I'm guessing this is a redis issue.

**Comment by rpd10** [comment]
I was able to move forward by pulling in a different version of redis-server using trial and error and the following Dockerfile:

```
FROM ubuntu:16.04
ENV REFRESHED_AT 2017-04-06
RUN apt-get -yqq update
RUN apt-get -yqq install software-properties-common python-software-properties
RUN add-apt-repository ppa:chris-lea/redis-server
RUN apt-get -yqq update
RUN apt-get -yqq install redis-server=3:3.2.8-1chl1~xenial1
RUN apt-get -yqq install redis-tools
EXPOSE 6379
ENTRYPOINT ["/usr/bin/redis-server", "--protected-mode no" ] 
CMD []
```

**Comment by VioletRainbows** [comment]
From what I've tested, the examples will run fine if you remove `--protected-mode no`.

**Comment by jamtur01** [comment]
This will be fixed in the next release.
