### ISSUE TITLE
How to update Dockerbook

### ISSUE THREAD

**Issue by ArtuGit** [turnbullpress/dockerbook-code#42]
I bought Dockerbook in November'16.
There is `Unlimited updates` options on the Dockerbook website.
Hot to update the book (get a new version)?

**Comment by jamtur01** [comment]
Use your existing download link.

**Comment by ArtuGit** [comment]
Where does this link exist?

**Comment by jamtur01** [comment]
In the email sent to you when you bought the book.

**Comment by ArtuGit** [comment]
What is the sender email address?
Regards, Artu

**Comment by jamtur01** [comment]
Email me - james@lovedthanlost.net - and I'll send you a new link.

**Comment by ArtuGit** [comment]
Thanks you.
