### ISSUE TITLE
redis container will not stay in the active statu

### ISSUE THREAD

**Issue by wddpct** [turnbullpress/dockerbook-code#46]
according to your https://github.com/turnbullpress/dockerbook-code/blob/master/code/5/sinatra/redis/Dockerfile, after running the 'docker run -d -P --name redis jamtur01/redis', redis will exit  immediately. may you should delete the ‘--protected-mode no’ parameter.

**Comment by jamtur01** [comment]
This will be fixed in the next release. Thanks!
