### ISSUE TITLE
Listing 5.70 - Running Docker-Jenkins image

### ISSUE THREAD

**Issue by stevepop** [turnbullpress/dockerbook-code#47]
Hi, 

I am a Mac user and  currently following the code on Chapter 5. I have built the Jenkins image, however when I run the container with the following, it returns the container ID and exits.
According to the instruction, I created jenkins_home in `/private/var/jenkins_home`. I also granted permission to the folder as follows; `sudo chown -R 1000 /private/var/jenkins_home`
Then I ran the image as follows;
```
docker run -d -p 8080:8080 -p 50000:50000 -v /private/var/jenkins_home:/var/jenkins_home -v /private/var/run/docker.sock:/var/run/docker.sock --name jenkins stevepop/jenkins
```
It returns the container ID but when I run `docker ps`, nothing displays. When I ran `docker ps -a`, I see the following;
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
decb7004b6fb        stevepop/jenkins    "/bin/tini -- /usr..."   4 seconds ago       Exited (1) 3 seconds ago                       jenkins
```
I suspect strongly that the problem is the volume mapping. When I remove the volumes, the container runs fine.

What could be the problem here please?

**Comment by jamtur01** [comment]
Any log output with an error?

**Comment by stevepop** [comment]
Hi @jamtur01,

Yes I got the following errors;
```
docker logs 9ef85f0fc8dc
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
Can not write to /var/jenkins_home/copy_reference_file.log. Wrong volume permissions?
touch: cannot touch '/var/jenkins_home/copy_reference_file.log': Permission denied
```

**Comment by jamtur01** [comment]
Is the UID of the jenkins user 1000?

**Comment by stevepop** [comment]
The container does not run so not sure how I can check the UID of jenkins user? The image below is the permisisons on the host
<img width="710" alt="permissions_osx" src="https://user-images.githubusercontent.com/526063/31101287-e05a45d4-a7c4-11e7-9066-7f67d896d3a0.png">

**Comment by jamtur01** [comment]
You can run the container without the volume and check.

**Comment by stevepop** [comment]
Yes the UID of jenkins user is 1000
<img width="556" alt="jenkins_uid" src="https://user-images.githubusercontent.com/526063/31101502-dcb16484-a7c5-11e7-8c80-cf03542229cd.png">

**Comment by stevepop** [comment]
HI @jamtur01, were you able to reproduce this issue? Is there an alternative way of getting past this point?

**Comment by jamtur01** [comment]
Sorry I haven't had a chance to replicate it. I won't have until the weekend. Do you have a Linux box you could use in the meantime?

**Comment by stevepop** [comment]
Okay, I will try on a Linux box in the meantime, thanks.
